name = "Tacit"
uuid = "1113dfd1-ddb9-4063-829d-27ff3979019a"
authors = ["Evgenii Petrov <blinunleius@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
